name: build_deploy_aks
on:
  push:
    paths:
      - unit4/exercise2/**
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code' 
        uses: actions/checkout@v3

      - name: 'Login to Azure Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 'Build and push the demoapp'
        run: |
          docker build unit4/exercise2/. -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx:${{ github.sha }}

      - name: 'Azure login'
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Set the target AKS cluster'
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.RESOURCE_GROUP_AKS }}' 
          cluster-name: '${{ secrets.CLUSTER_NAME }}'
      
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      
      - name: Replace image name in manifest
        run: |
          sed -i 's/__REGISTRY-LOGIN-SERVER__/${{ secrets.REGISTRY_LOGIN_SERVER }}/g' unit4/exercise2/deployment.yaml

      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'default'
          manifests: |
            unit4/exercise2/deployment.yaml
            unit4/exercise2/service.yaml
          images: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx:${{ github.sha }}

      - name: 'Get public IP of demoapp'
        id: getip
        run: |
          kubectl get service -l tier=networking
